/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiAbsensi;

/**
 *
 * @author Asus
 */
public class OptionMenuSiswa extends javax.swing.JInternalFrame {

    /**
     * Creates new form OptionMenu
     */
    public OptionMenuSiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rekapHarianForm = new javax.swing.JButton();
        rekapMingguanFrom = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        absensi = new javax.swing.JButton();

        setTitle("OPTION MENU");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        rekapHarianForm.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        rekapHarianForm.setText("Rekap Harian");
        rekapHarianForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapHarianFormActionPerformed(evt);
            }
        });

        rekapMingguanFrom.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        rekapMingguanFrom.setText("Rekap Mingguan");
        rekapMingguanFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapMingguanFromActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        absensi.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        absensi.setText("Absensi");
        absensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absensiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(absensi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(rekapHarianForm)
                .addGap(49, 49, 49)
                .addComponent(rekapMingguanFrom)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rekapHarianForm)
                    .addComponent(rekapMingguanFrom)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(absensi))
                .addContainerGap(261, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rekapHarianFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapHarianFormActionPerformed
        // TODO add your handling code here:
        RekapHarianSiswa rekapHarian = new  RekapHarianSiswa();
        rekapHarian.setVisible(true);
        this.getDesktopPane().add(rekapHarian);
        this.dispose();
    }//GEN-LAST:event_rekapHarianFormActionPerformed

    private void rekapMingguanFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapMingguanFromActionPerformed
        // TODO add your handling code here:
        RekapMingguanSiswa rekapMingguan = new  RekapMingguanSiswa();
        rekapMingguan.setVisible(true);
        this.getDesktopPane().add(rekapMingguan);
        this.dispose();                  
    }//GEN-LAST:event_rekapMingguanFromActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         LoginFormSiswa optionMenu = new LoginFormSiswa();
        optionMenu.setVisible(true);
        this.getDesktopPane().add(optionMenu);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void absensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absensiActionPerformed
        // TODO add your handling code here:
        AbsensiFormSiswa absensiFormSiswa = new AbsensiFormSiswa();
        absensiFormSiswa.setVisible(true);
        this.getDesktopPane().add(absensiFormSiswa);
        this.dispose();

    }//GEN-LAST:event_absensiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton absensi;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rekapHarianForm;
    private javax.swing.JButton rekapMingguanFrom;
    // End of variables declaration//GEN-END:variables
}
